package org.peanut.distributedemo.model;

public class OrderItem extends OrderItemKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.buynum
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    private Integer buynum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.buynum
     *
     * @return the value of order_item.buynum
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public Integer getBuynum() {
        return buynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.buynum
     *
     * @param buynum the value for order_item.buynum
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public void setBuynum(Integer buynum) {
        this.buynum = buynum;
    }
}