package org.peanut.distributedemo.model;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.money
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.receiverAddress
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    private String receiveraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.receiverName
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    private String receivername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.receiverPhone
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    private String receiverphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.paystate
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    private Integer paystate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ordertime
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.money
     *
     * @return the value of order.money
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.money
     *
     * @param money the value for order.money
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.receiverAddress
     *
     * @return the value of order.receiverAddress
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public String getReceiveraddress() {
        return receiveraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.receiverAddress
     *
     * @param receiveraddress the value for order.receiverAddress
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public void setReceiveraddress(String receiveraddress) {
        this.receiveraddress = receiveraddress == null ? null : receiveraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.receiverName
     *
     * @return the value of order.receiverName
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public String getReceivername() {
        return receivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.receiverName
     *
     * @param receivername the value for order.receiverName
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public void setReceivername(String receivername) {
        this.receivername = receivername == null ? null : receivername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.receiverPhone
     *
     * @return the value of order.receiverPhone
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public String getReceiverphone() {
        return receiverphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.receiverPhone
     *
     * @param receiverphone the value for order.receiverPhone
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public void setReceiverphone(String receiverphone) {
        this.receiverphone = receiverphone == null ? null : receiverphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.paystate
     *
     * @return the value of order.paystate
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public Integer getPaystate() {
        return paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.paystate
     *
     * @param paystate the value for order.paystate
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public void setPaystate(Integer paystate) {
        this.paystate = paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ordertime
     *
     * @return the value of order.ordertime
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.ordertime
     *
     * @param ordertime the value for order.ordertime
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbg.generated Tue Dec 22 23:14:42 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}